FROM alpine:3

ARG BUILD_VERSION

LABEL org.opencontainers.image.source=https://github.com/davison/ha-sinkhole/dns-node
LABEL org.opencontainers.image.description="DNS resolver that uses provided blocklists and then forwards to configured upstream resolvers."
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.version="$BUILD_VERSION"

# Install coredns (which creates the user), gettext (for envsubst),
# and su-exec (to drop privileges)
RUN apk add --no-cache coredns gettext su-exec bash

COPY Corefile.template /etc/coredns/Corefile.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Entrypoint will run as root by default
ENTRYPOINT ["/entrypoint.sh"]

# This CMD is passed as arguments ("$@") to the entrypoint.
# This is the default CoreDNS config path.
CMD ["-conf", "/etc/coredns/Corefile"]
